# Generated by Django 2.2.3 on 2020-01-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20200130_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Likes',
            new_name='likes',
        ),
    ]
